"""uid fixed for books model

Revision ID: 2a88729dbd5d
Revises: 6ee9736cad5d
Create Date: 2025-07-13 01:44:33.194725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a88729dbd5d'
down_revision: Union[str, Sequence[str], None] = '6ee9736cad5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'uid',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.create_index(op.f('ix_books_uid'), 'books', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_uid'), table_name='books')
    op.alter_column('books', 'uid',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
